[package]
name = "music"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.13", features = ["rustls", "cookies", "socks"] }
tokio = { version = "1.49", features = ["full"] }
